export { default as Instructions } from './instructions/instructions';
export { default as Result } from './playground/components/result/result';
export { default as Playground } from './playground/playground';
export { default as Exam } from './exam/Exam';
export * from './login/login';
export * from './register/register';
export * from './home/home';
export { default as Teste } from './teste/teste';
export * from './adm/dashboard/dashboard';
export * from './adm/adm';
